server.port: 8082
#数据库名称
spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
    name: user
#数据库连接url
    url: jdbc:mysql://localhost:3306/user
#用户名
    username: root
#密码
    password: root
#数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置映射文件
  mybatis:
    mapper-locations: classpath:/mapper/*.xml
    #配置实体类
    type-aliases-package: com.mcy.springbootswagger.User
#hikari
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 500000
      max-lifetime: 540000
      connection-timeout: 60000
      connection-test-query: SELECT 1
#Druid
    druid:
      name: user
          #数据库连接url
      url: jdbc:mysql://localhost:3306/user
          #用户名
      username: root
          #密码
      password: root
          #数据库驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 10
      maxActive: 20
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      validationQuery: SELECT 1
      validation-query-timeout: 500
      filters: stat
    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: create-drop

  mvc:
    hiddenmethod:
      filter:
        enabled: true
    pathmatch:
      matching-strategy: ant_path_matcher
thymeleaf:
  prefix: classpath:/templates  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  mode: HTML5
swagger:
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.4.0.RELEASE
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
  contact:
    name: didi
    url: http://blog.didispace.com
    email: dyc87112@qq.com
  base-package: com.didispace
  base-path: /**
